version: "3"

services:
  bind:
    container_name: bind
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-bind:1.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - './etc-bind:/etc/bind'
    restart: always
